language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_54c4a204f4b6_key -iv $encrypted_54c4a204f4b6_iv 
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties 
   -d
